/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jiří Kuba (https://sketchfab.com/kuba.jirka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/diamond-0363f038a3ad4c5da234490c9879805e
title: Diamond
*/

import React from 'react'
import {useGLTF} from '@react-three/drei'

interface DiamondProps{
    position: number
}

export function Diamond({ position }: DiamondProps) {
    const {nodes, materials}: any = useGLTF('/scene.gltf')
    return (
        <group scale={1}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Diamond_0.geometry} material={materials.DiamondMaterial} scale={2}
                      position={[position, position, position]}/>
            </group>
        </group>
    )
}

useGLTF.preload('/scene.gltf')
