/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jiří Kuba (https://sketchfab.com/kuba.jirka)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/diamond-0363f038a3ad4c5da234490c9879805e
title: Diamond
*/

import React from 'react'
import {useGLTF} from '@react-three/drei'
import {useThree} from "@react-three/fiber";

interface DiamondProps {
    position: number
}

export function Diamond({position}: DiamondProps) {

    const {nodes, materials}: any = useGLTF('/scene.gltf')
    const state = useThree()

    return (
        <group scale={1} onAfterRender={() => {
           // console.log(state.scene.children[14].rotation)
        }}>
            <group>
                <mesh geometry={nodes.Object_4.geometry} material={materials["Material.001"]} scale={1}
                      position={[position, position, position]}/* rotation={[0, 0, -1.57]}*/>
                    <meshStandardMaterial color={'#B9F2FF'} metalness={3.5}/>
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('/scene.gltf')
